### ISSUE TITLE
[BUG] Every hour the same announcement is repeated

### ISSUE THREAD

**Issue by VuzzyM** [vbloher/monitoring-tool#2]
Hi, there is a bug where every hour the same announcement is repeated, but actually the server does not crash and the server is not spelled correctly.

![image](https://github.com/nodejumper-org/monitoring-tool/assets/66425682/f3ed9bbc-6c75-4078-b8b6-81e7abd67d83)
![image](https://github.com/nodejumper-org/monitoring-tool/assets/66425682/c1cc014a-27ea-4f2e-adfd-03f6a1eccc02)
![image](https://github.com/nodejumper-org/monitoring-tool/assets/66425682/c02ffc54-c7fb-4298-bebd-bf5c3a3c30c0)

**Comment by vbloher** [comment]
Hi. check your configuration. this message means that monitoring tool was unable to reach the server or node
